### PR TITLE
Build extension thanks to ant

### PR DESCRIPTION
**Pull request by adriangibanelbtactic**
Now the installer builds the installer within Zimbra.
Note: This was only tested in a ZCS 8.7 machine.
Feedback in a ZCS 8.8 machine is welcomed.

Code assumes this is going to be merged into Zimbra-Community default branch .

E.g. If you want to test it you will have to make sure the git clone command changes to your own branch "-b branch" and finally you will have to download your raw file from your the test branch and not from the official instructions raw file.

### CODE REVIEW

**Comment by adriangibanelbtactic** [comment]
> Please note, that I no longer support 8.7 (if though it says so in the readme)
Yeah, I know. That's why I made it clear. 
I might clone/upgrade my test machine to 8.8 in a near future. 

> **Can you test your work on a clean CentOS 7 with the latest version of Zimbra.
As I said before I might try Ubuntu 1604 and latest version of Zimbra. 

> Most likely the installer will not work, as it assumes ant is installed, and
> that will not be the case in most cases. So you need to add it to the yum/apt
> install including all other things you may need.**
I thought I was using zimbra's JRE's ant command. 
That's why it didn't make sense to me for making sure it was installed in the installer script. 
Now I'm checking that there is no such ant binary in the installed zimbra files. 

So you are right on this point. 

> Removing .idea and lib folders etc, may be good, but it will slow me down
> developing this. So I am not too happy about it.
I know you were going to comment about that :). The way I see it you need to add them in a new commit as if this project had used the ant method of building it since its start and you came as a new developer. 

Why? 
Because those folders need to be added empty with the .gitignore file so that no binaries are no longer present in the repo (except in git history). 

Then the final jar path has to be the same one in both build types. 

I'm outputting it to dist/ and you used out/ . 

Either you need to change idea paths to use dist or... change the ant path.

**Comment by adriangibanelbtactic** [comment]
> Most likely the installer will not work, as it assumes ant is installed, and
> that will not be the case in most cases. So you need to add it to the yum/apt
> install including all other things you may need.

I suspect that some of the Zimbra packages (probably libreoffice)  do install ant anyways but it's better to be sure as you suggest.

**Comment by barrydegraaff** [comment]
There is no zimbra libreoffice rpm on by ZCS....

**Comment by adriangibanelbtactic** [comment]
> There is no zimbra libreoffice rpm on by ZCS....

You might be right on it.
It's a suggested package when you want some previews to work though.

**Comment by barrydegraaff** [comment]
That is network edition only.

**Comment by barrydegraaff** [comment]
closed via https://github.com/Zimbra-Community/shared-mailbox-toolkit/pull/25

**Pull request closed without merging**
