### PR TITLE
Build thanks to ant v2

### PR DESCRIPTION
**Pull request by adriangibanelbtactic**
This is another approach to build the extension thanks to ant.
It's not meant to be merged because it's not tested in ZCS 8.8 yet.
It's meant to get feedback from upstream.

Thank you for your input.

### CODE REVIEW

**Comment by adriangibanelbtactic** [comment]
This is how I do my tests:

```
wget https://raw.githubusercontent.com/btactic/shared-mailbox-toolkit/build-thanks-to-ant-v2/shared-mailbox-toolkit-installer.sh -O /tmp/shared-mailbox-toolkit-installer.sh
chmod +rx /tmp/shared-mailbox-toolkit-installer.sh
```
Edit: /tmp/shared-mailbox-toolkit-installer.sh so that:
```
git clone --depth=1 git://github.com/Zimbra-Community/shared-mailbox-toolkit
```
is replaced to:
```
git clone --depth=1 git://github.com/btactic/shared-mailbox-toolkit -b build-thanks-to-ant-v2
```

Finally:
```
/tmp/shared-mailbox-toolkit-installer.sh
```

**Comment by adriangibanelbtactic** [comment]
Using: Instructions from comment: https://github.com/Zimbra-Community/shared-mailbox-toolkit/pull/25#issuecomment-459864716 I was able to test this branch in Ubuntu 16.04 with ZCS 8.8.11 .
So currently the test status for this pull request is:

- [ OK ] ZCS 8.8.11 - Ubuntu 16.04
- [ Pending ] ZCS 8.8.11 - Ubuntu 16.04

**Comment by adriangibanelbtactic** [comment]
Using: Instructions from comment: [#25 (comment)](https://github.com/Zimbra-Community/shared-mailbox-toolkit/pull/25#issuecomment-459864716) I was able to test this branch in CentOS 7 with ZCS 8.8.11 .
So currently the test status for this pull request is:

* [ OK ] ZCS 8.8.11 - Ubuntu 16.04
* [ OK ] ZCS 8.8.11 - CentOS 7

@barrydegraaff Is it ok now for merging the branch?

Thank you very much!

**Comment by barrydegraaff** [comment]
Looks good, I will merge it soon

**Pull request closed without merging**
